services:
  postgres:
    container_name: "db_users"
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database/users:/var/lib/postgresql/data/
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:4000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
