services:
  postgres:
    container_name: 'db_users'
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./backend/database/users:/var/lib/postgresql/data/
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    ports:
      - "${BACKEND_PORT}:4000"
  
networks:
  app-network:
    driver: bridge