services:
  postgres:
    container_name: "db_users"
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/database/users:/var/lib/postgresql/data/
    networks:
      - app-network

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
    ports:
      - "${BACKEND_PORT}:4000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONTEND_PORT}:3000"
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

networks:
  app-network:
    driver: bridge
