name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-backend:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (Backend)
        run: |
          cd backend
          yarn install

      - name: Run lint (Backend)
        run: |
          cd backend
          yarn lint

      - name: Run Prettier check (Backend)
        run: |
          cd backend
          yarn prettier:check

  lint-frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          yarn install

      - name: Run lint (Frontend)
        run: |
          cd frontend
          yarn run lint

      # - name: Run Prettier check (Frontend)
      #   run: |
      #     cd frontend
      #     yarn prettier:check

  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    needs: [lint-backend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (Backend)
        run: |
          cd backend
          yarn install

      - name: Run tests (Backend)
        run: |
          cd backend
          yarn test

      - name: Build Backend
        run: |
          cd backend
          yarn build

  build-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    needs: [lint-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies (Frontend)
        run: |
          cd frontend
          yarn install

      - name: Run tests (Frontend)
        run: |
          cd frontend
          yarn test

      - name: Build Frontend
        run: |
          cd frontend
          yarn build

  docker-build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: backend:latest

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: frontend:latest

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend and frontend
        run: |
          echo "Deploying Backend and Frontend"
